services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ManutencaoEquipamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ManutencaoEquipamentos
    volumes:
      - ./src:/app/src  # Mapeamento do diret칩rio de c칩digo-fonte local para o container
      - ./target:/app/target  # Mapeamento do diret칩rio target (se necess치rio)
