services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ManutencaoEquipamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3000:3000"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ManutencaoEquipamentos