services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ManutencaoEquipamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./manutencao-equipamentos-back # Ajuste para o caminho correto do backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ManutencaoEquipamentos
    depends_on:
      - db
    networks:
      - app-network
    dns:
      - 8.8.8.8  # Google's public DNS server
      - 8.8.4.4  # Backup Google DNS

  frontend:
    build:
      context: ./manutencao-equipamentos-front # Ajuste para o caminho correto do frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: production
    networks:
      - app-network

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "8025:8025"  # Web UI
#      - "1025:1025"  # SMTP server
#    networks:
#      - app-network
networks:
  app-network:
    driver: bridge
