services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ManutencaoEquipamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    networks:
      - app-network

  backend:
    build:
      context: ./manutencao-equipamentos-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./manutencao-equipamentos-back:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ManutencaoEquipamentos
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecret
    depends_on:
      - db
    networks:
      - app-network
    dns:
      - 8.8.8.8  # Google's public DNS server
      - 8.8.4.4  # Backup Google DNS

  frontend:
    build:
      context: ./manutencao-equipamentos-front
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./manutencao-equipamentos-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    user: "node:node"

networks:
  app-network:
    driver: bridge
